#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export NVM_DIR="/Users/wesley/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

alias nvm-upgrade-latest="nvm install node --reinstall-packages-from=node"
alias zprezto-update="cd ~/.zprezto && git pull && git submodule update --init --recursive"
alias reload="exec zsh"
alias rmnodemodules="rm -f package-lock.json && rm -rf node_modules && npm i"
alias rmyarnmodules="rm -f yarn.lock && rm -f package-lock.json && rm -rf node_modules && yarn"
#alias redis-up="redis-server /usr/local/etc/redis.conf"

function precmd() {
  echo -ne "\033]0;${PWD##*/}\007"
}

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /Users/wesley/Developer/auth-service/node_modules/tabtab/.completions/serverless.zsh ]] && . /Users/wesley/Developer/auth-service/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /Users/wesley/Developer/auth-service/node_modules/tabtab/.completions/sls.zsh ]] && . /Users/wesley/Developer/auth-service/node_modules/tabtab/.completions/sls.zsh

# POWERLEVEL9K
# POWERLEVEL9K_MODE='awesome-patched'
# POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(user dir node_version vcs)
# POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs history time)

# tabtab source for slss package
# uninstall by removing these lines or running `tabtab uninstall slss`
[[ -f /Users/wesley/Developer/vslr/journey-service/node_modules/tabtab/.completions/slss.zsh ]] && . /Users/wesley/Developer/vslr/journey-service/node_modules/tabtab/.completions/slss.zsh
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
