#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export NVM_DIR="/Users/wesley/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

alias nvm-upgrade-latest="nvm install node --reinstall-packages-from=node"
alias zprezto-update="cd ~/.zprezto && git pull && git submodule update --init --recursive"
#alias redis-up="redis-server /usr/local/etc/redis.conf"

function precmd() {
  echo -ne "\033]0;${PWD##*/}\007"
}
